# Main build jobs for CI/CD on Azure Pipelines.

parameters:
- name: builds
  type: object
  default:

  - name: linux_37
    vmImage: ubuntu-20.04
    primaryBuild: true
    vars:
      PYTHON_SERIES: "3.7"

  - name: linux_38
    vmImage: ubuntu-20.04
    primaryBuild: true
    vars:
      PYTHON_SERIES: "3.8"

  - name: macos_37
    vmImage: macos-10.15
    primaryBuild: false
    vars:
      PYTHON_SERIES: "3.7"

  - name: macos_38
    vmImage: macos-10.15
    primaryBuild: false
    vars:
      PYTHON_SERIES: "3.8"

  - name: windows_37
    vmImage: windows-2019
    primaryBuild: false
    vars:
      PYTHON_SERIES: "3.7"

  - name: windows_38
    vmImage: windows-2019
    primaryBuild: false
    vars:
      PYTHON_SERIES: "3.8"

jobs:
- ${{ each build in parameters.builds }}:
  - job: ${{ format('build_{0}', build.name) }}
    pool:
      vmImage: ${{ build.vmImage }}
    variables:
      ${{ insert }}: ${{ build.vars }}
    steps:

    - template: azure-job-setup.yml
      parameters:
        setupBuild: true

    - bash: |
        conda create -n build setuptools pip python="$PYTHON_SERIES"
        conda activate build
        pip install $PIPELINE_WORKSPACE/sdist/*.tar.gz
      displayName: Install from sdist
